channels:
  - conda-forge
  - defaults
dependencies:
  - scipy
  - numba
  - xarray
  - netcdf4
  - pandas
  - bokeh
  - panel
  - param
  - hvplot
  - holoviews
  - jupyter
  - nbconvert
  - sympy
  - numpy
  - dill
  - cmocean

